apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      -  name: front
         image: docker.io/alinawazmamdani/backend
         ports:
         - containerPort: 8085
         env:
         -  name: MYSQL_IP
            value: mysql


